version: '3.8'

services:
  # Production build
  contest-draw:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.contest-draw.rule=Host(`contest-draw.localhost`)"
      - "traefik.http.services.contest-draw.loadbalancer.server.port=80"

  # Development with hot reload
  contest-draw-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: bun run dev
    profiles:
      - dev

networks:
  default:
    name: contest-draw-network
