name: Complete CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1' # Weekly security scan on Monday at 2 AM UTC

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Phase 1: Code Testing & Quality Checks
  code-tests:
    runs-on: ubuntu-latest
    outputs:
      tests-passed: ${{ steps.test-result.outcome == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun Runtime
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install Dependencies
      run: bun install
      
    - name: Run Unit Tests with Coverage
      id: test-result
      run: bun run test:coverage
      
    - name: Upload Test Coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  # Phase 2: Application Build & Packaging
  application-build:
    runs-on: ubuntu-latest
    needs: code-tests
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun Runtime
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install Dependencies
      run: bun install
      
    - name: Build Production Application
      run: bun run build
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: production-build
        path: dist/

  # Phase 3: Application Security Scan
  application-security-scan:
    runs-on: ubuntu-latest
    needs: application-build
    permissions:
      contents: read
      security-events: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun Runtime
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install Dependencies
      run: bun install
      
    - name: Build Application for Security Scan
      run: bun run build
      
    - name: Run Trivy Filesystem Vulnerability Scan
      id: trivy-fs
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-fs-results.sarif'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true
        
    - name: Upload Security Scan Results to GitHub
      uses: github/codeql-action/upload-sarif@v3
      if: always() && steps.trivy-fs.outcome == 'success'
      with:
        sarif_file: 'trivy-fs-results.sarif'
        
    - name: Display Vulnerability Report
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true

  # Phase 4: Container Image Build
  container-build:
    runs-on: ubuntu-latest
    needs: application-build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Production Container Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: jambo-draw-winner:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Verify Container Image Build
      run: |
        echo "✅ Docker container image built successfully"
        docker images jambo-draw-winner:latest

  # Phase 5: Container Security Scan
  container-security-scan:
    runs-on: ubuntu-latest
    needs: container-build
    permissions:
      contents: read
      security-events: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Trivy Container Vulnerability Scan
      id: trivy-container
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'image'
        scan-ref: 'jambo-draw-winner:latest'
        format: 'sarif'
        output: 'trivy-container-results.sarif'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true
        
    - name: Upload Container Security Scan Results to GitHub
      uses: github/codeql-action/upload-sarif@v3
      if: always() && steps.trivy-container.outcome == 'success'
      with:
        sarif_file: 'trivy-container-results.sarif'
        
    - name: Display Container Vulnerability Report
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'image'
        scan-ref: 'jambo-draw-winner:latest'
        format: 'table'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true

  # Phase 6: Production Deployment
  production-deployment:
    runs-on: ubuntu-latest
    needs: [code-tests, application-build, application-security-scan, container-build, container-security-scan]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun Runtime for Deployment
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install Dependencies
      run: bun install
        
    - name: Build Application for Production
      run: bun run build
        
    - name: Upload Production Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: production-deployment
        path: dist/